language: c
sudo: required
matrix:
  include:
  - os: linux
    dist: trusty
  - os: osx
    osx_image: xcode8
  - os: osx
    osx_image: xcode8.3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qqy python-apt python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo easy_install pip; fi
install:
- sudo -H pip install --upgrade ansible
- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- ansible-playbook -i tests/inventory tests/test.yml --connection=local
- 'ansible-playbook -i tests/inventory tests/test.yml --connection=local |
  grep -q ''changed=0.*failed=0'' && (echo ''Idempotence test: pass'' && exit 0) ||
  (echo ''Idempotence test: fail'' && exit 1)'
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
