---

- name: MONIT | Ensure monit group
  group:
    name: "{{ monit_group }}"

- name: MONIT | Ensure monit user
  user:
    name: "{{ monit_user }}"
    group: "{{ monit_group }}"
    home: /bin/false
    createhome: yes

- name: Include OS-specific tasks | Debian.
  import_tasks: Debian/pkg.yml
  tags: monit_pkg
  when: not monit_install_from_source

- name: Install from source
  import_tasks: Debian/install.yml
  tags: monit_install
  when: monit_install_from_source

- import_tasks: autostart.yml
  tags: monit_autostart
  become: true
  when: monit_install_from_source
